Import('env')

ekvs_files = Glob('*.c', strings=True)

libekvs_ccflags = ['-std=c89','-Werror','-pedantic']

libekvs = env.StaticLibrary('ekvs',
   ekvs_files,
   CPPPATH = ['.'],
   CCFLAGS = libekvs_ccflags + env['CCFLAGS'],
   LIBS=[], 
   LIBPATH=[]
)
Return('libekvs')