Import('env')

ekvs_files = Glob('*.c', strings=True)

libekvs = env.StaticLibrary('ekvs',
   ekvs_files,
   CPPPATH = ['.'] + env['EKVS_INCLUDE'],
   CCFLAGS = env['CCFLAGS'],
   LIBS=[], 
   LIBPATH=[]
)
Return('libekvs')